name: lukehopkins
favicon: null
layout_spectrum: 0.50432
typography_spectrum: 0.74215
title: Luke Hopkins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9f7'
    - '#7eb2e7'
    - '#1c1b28'
    - '#5d5e62'
    - '#94857f'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
