name: lukehopkins
favicon: null
layout_spectrum: 0.1977015226148069
typography_spectrum: 0.6055946010164917
title: Luke Hopkins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.016177534824237227
  lightness: 0.7221485001500696
  saturation: 0.6221555722877383
  rhythmicContrast: 0.6862923421431333
purpose: []
